name: spawn_hybrid
publish_to: none
environment:
  sdk: ^3.7.0
resolution: workspace
dependencies:
  async: ^2.9.0
  path: ^1.8.2
  stream_channel: ^2.1.0
dev_dependencies:
  other_package:
    path: other_package/
  test: any
