name: fake_async
version: 1.0.1
description: Fake asynchronous events such as timers and microtasks for deterministic testing.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/fake_async

environment:
  sdk: '>=2.0.0-dev.36.0 <3.0.0'

dependencies:
  clock: '^1.0.0'
  collection: '^1.8.0'

dev_dependencies:
  async: '>=1.10.0 <3.0.0'
  test: '^0.12.28'
