name: fake_async
version: 1.1.0
description: Fake asynchronous events such as timers and microtasks for deterministic testing.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/fake_async

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  clock: ^1.0.0
  collection: ^1.8.0

dev_dependencies:
  async: ^2.0.0
  test: ^1.0.0
