name: fake_async
version: 1.3.2
description: >-
  Fake asynchronous events such as timers and microtasks for deterministic
  testing.
repository: https://github.com/dart-lang/test/tree/master/pkgs/fake_async
environment:
  sdk: ^3.3.0

dependencies:
  clock: ^1.1.0
  collection: ^1.15.0

dev_dependencies:
  async: ^2.5.0
  dart_flutter_team_lints: ^2.0.0
  test: ^1.16.0
  matcher: any
