language: dart

dart:
  - stable
  - dev

dart_task:
  - test: -p vm
    xvfb: false
  - test: -p firefox
  - dartanalyzer

matrix:
  include:
  - dart: stable
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
