name: matcher

# This version should really be 0.12.1-dev, but test depends on matcher <0.12.1,
# so we're using + instead.
version: 0.12.0+dev
author: Dart Team <misc@dartlang.org>
description: Support for specifying test expectations
homepage: https://github.com/dart-lang/matcher
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
