name: matcher
version: 0.12.3-dev
author: Dart Team <misc@dartlang.org>
description: Support for specifying test expectations
homepage: https://github.com/dart-lang/matcher
environment:
  sdk: '>=2.0.0-dev.17.0 <2.0.0'
dependencies:
  stack_trace: '^1.2.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'

dependency_overrides:
  test: ^0.12.0
