name: matcher
version: 0.12.5

description: >-
  Support for specifying test expectations via an extensible Matcher class.
  Also includes a number of built-in Matcher implementations for common cases.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/matcher

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stack_trace: ^1.2.0

dev_dependencies:
  pedantic: ^1.4.0
  test: '>=0.12.0 <2.0.0'

dependency_overrides:
  test: ^1.3.0
