name: matcher

version: 0.12.1+1
author: Dart Team <misc@dartlang.org>
description: Support for specifying test expectations
homepage: https://github.com/dart-lang/matcher
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
