name: matcher
version: 0.12.16+1
description: >-
  Support for specifying test expectations via an extensible Matcher class.
  Also includes a number of built-in Matcher implementations for common cases.
repository: https://github.com/dart-lang/matcher

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.10.0
  meta: ^1.8.0
  stack_trace: ^1.10.0
  term_glyph: ^1.2.0
  test_api: ">=0.5.0 <0.8.0"

dev_dependencies:
  fake_async: ^1.3.0
  lints: ^3.0.0
  test: ^1.23.0
