name: test_process
version: 2.0.3
description:
  "Test processes: starting; validating stdout and stderr; checking exit code"
repository: https://github.com/dart-lang/test_process

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async: ^2.5.0
  meta: ^1.3.0
  path: ^1.8.0
  test: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test_descriptor: ^2.0.0
