name: test_process
version: 1.0.6-dev

description: A package for testing subprocesses.
homepage: https://github.com/dart-lang/test_process

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  async: ^2.0.0
  meta: ^1.0.0
  path: ^1.0.0
  test: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test_descriptor: ^1.0.0
