name: test_process
version: 2.1.1
description: |
  Test processes: starting; validating stdout and stderr; checking exit code
repository: https://github.com/dart-lang/test/tree/master/pkgs/test_process

environment:
  sdk: ^3.1.0

dependencies:
  async: ^2.5.0
  meta: ^1.3.0
  path: ^1.8.0
  test: ^1.16.6

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test_descriptor: ^2.0.0
