name: nnbd_opted_out
publish_to: none
environment:
  sdk: '>=2.11.0 <3.0.0'
dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  test: any
dependency_overrides:
  test:
    path: ../../pkgs/test
  test_api:
    path: ../../pkgs/test_api
  test_core:
    path: ../../pkgs/test_core
  matcher:
    git:
      url: https://github.com/dart-lang/matcher.git
      ref: 3fc9b3c35c3c0465ebef9158971f8203a4fc9416
