name: test_analyzer_plugin
description: An analyzer plugin to report improper usage of the test package.
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.5

dev_dependencies:
  analyzer_testing: ^0.1.7
  test: any
  test_reflective_loader: any
