language: dart

dart:
  - dev
  - 2.1.0

dart_task:
  - test

matrix:
  include:
  - dart: dev
    dart_task: dartfmt
  - dart: dev
    dart_task:
      dartanalyzer: --fatal-infos --fatal-warnings .
  - dart: 2.1.0
    dart_task:
      dartanalyzer: --fatal-warnings .

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
