name: test_descriptor
version: 2.0.1-dev
description: An API for defining and verifying directory structures.
homepage: https://github.com/dart-lang/test_descriptor

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.5.0
  collection: ^1.15.0
  matcher: ^0.12.10
  meta: ^1.3.0
  path: ^1.8.0
  term_glyph: ^1.2.0
  test: ^1.16.0

dev_dependencies:
  lints: ^1.0.0
