name: checks
version: 0.3.1
description: >-
  A framework for checking values against expectations and building custom
  expectations.
repository: https://github.com/dart-lang/test/tree/master/pkgs/checks
issue_tracker: https://github.com/dart-lang/test/issues?q=is%3Aissue+is%3Aopen+label%3Apackage%3Achecks

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  async: ^2.8.0
  meta: ^1.9.0
  test_api: ">=0.5.0 <0.8.0"

dev_dependencies:
  test: ^1.21.3
