name: checks
version: 0.2.3-wip
description: >-
  A framework for checking values against expectations and building custom
  expectations.
repository: https://github.com/dart-lang/test/tree/master/pkgs/checks

environment:
  sdk: ^3.0.0

dependencies:
  async: ^2.8.0
  meta: ^1.9.0
  test_api: ">=0.5.0 <0.7.0"

dev_dependencies:
  dart_flutter_team_lints: ^1.0.0
  test: ^1.21.3
