name: checks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.8.0
  test_api: ^0.4.0

dev_dependencies:
  test: ^1.21.3

dependency_overrides:
  test_api:
    path: ../test_api
  test_core:
    path: ../test_core
  test:
    path: ../test
