name: checks
version: 0.1.1-dev
description: >-
  A framework for checking values against expectations and building custom
  expectations.
repository: https://github.com/dart-lang/test/tree/master/pkgs/checks

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  async: ^2.8.0
  test_api: ^0.4.0

dev_dependencies:
  test: ^1.21.3
  lints: ^2.0.0
